=== mia-platform/micro-lc/packages/interfaces/schemas/v2/config.schema.json
{
  "$id": "https://raw.githubusercontent.com/micro-lc/micro-lc/main/packages/interfaces/schemas/v2/config.schema.json#",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Config",
  "description": "Version 2 of micro-lc configuration",
  "definitions": {
    "settings": {
      "title": "Settings",
      "type": "object",
      "properties": {
        "4xx": {
          "type": "object",
          "patternProperties": {
            "^4\\d{2}$": {
              "oneOf": [
                {
                  "$ref": "#/definitions/iframeApplication",
                  "type": "object",
                  "required": ["integrationMode", "src"]
                },
                {
                  "$ref": "#/definitions/composableApplication",
                  "type": "object",
                  "required": ["integrationMode", "config"]
                },
                {
                  "$ref": "#/definitions/parcelApplication",
                  "type": "object",
                  "required": ["integrationMode", "entry"]
                }
              ]
            }
          }
        },
        "5xx": {
          "type": "object",
          "default": {
            "500": {
              "entry": "./500.html",
              "integrationMode": "parcel"
            }
          },
          "patternProperties": {
            "^5\\d{2}$": {
              "oneOf": [
                {
                  "$ref": "#/definitions/iframeApplication",
                  "type": "object",
                  "required": ["integrationMode", "src"]
                },
                {
                  "$ref": "#/definitions/composableApplication",
                  "type": "object",
                  "required": ["integrationMode", "config"]
                },
                {
                  "$ref": "#/definitions/parcelApplication",
                  "type": "object",
                  "required": ["integrationMode", "entry"]
                }
              ]
            }
          }
        },
        "composerUri": {
          "description": "The URI where the composer plugin can be found, if needed",
          "type": "string",
          "format": "uri-reference"
        },
        "mountPoint": {
          "$ref": "https://raw.githubusercontent.com/micro-lc/micro-lc/main/packages/interfaces/schemas/v2/plugin.schema.json#/definitions/content"
        },
        "mountPointSelector": {
          "description": "Query selector to plugins mounting DOM element",
          "type": "string",
          "default": "#__MICRO_LC_MOUNT_POINT",
          "examples": [
            "#my-plugin-container",
            "body micro-lc custom-layout div#plugin-container"
          ]
        },
        "defaultUrl": {
          "description": "Landing URL",
          "type": "string",
          "default": "/",
          "examples": ["/my-awesome-plugin"],
          "format": "uri-reference"
        }
      },
      "additionalProperties": false
    },

    "css": {
      "title": "CSSConfig",
      "type": "object",
      "properties": {
        "nodes": {
          "description": "A map matching CSS selectors to rules",
          "type": "object",
          "examples": [
            {
              ":host": {
                "width": "100%"
              }
            }
          ],
          "patternProperties": {
            ".*": {
              "description": "A valid CSS selector",
              "type": "object",
              "patternProperties": {
                ".*": {
                  "description": "A valid CSS property",
                  "oneOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "number"
                    }
                  ]
                }
              }
            }
          }
        },
        "global": {
          "description": "Standard CSS variables globally available scoped with prefix '--micro-lc-'",
          "type": "object",
          "properties": {
            "primary-color": {
              "type": "string"
            },
            "font-family": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "iframeApplication": {
      "title": "IFrameApplication",
      "type": "object",
      "examples": [
        {
          "integrationMode": "iframe",
          "src": "www.google.com",
          "route": "/embedded-google-page",
          "attributes": {
            "allow": "fullscreen"
          }
        }
      ],
      "properties": {
        "integrationMode": {
          "description": "Type of the application: nested browsing context",
          "const": "iframe"
        },
        "src": {
          "description": "iFrame src attribute value",
          "type": "string",
          "examples": ["/frame.html", "https://mydomain.com/"]
        },
        "srcdoc": {
          "description": "iFrame html content",
          "type": "string",
          "examples": [
            "<!DOCTYPE><html><head></head><body>IFrame Content</body></html>"
          ]
        },
        "route": {
          "description": "Path on which the iFrame will be rendered",
          "type": "string"
        },
        "attributes": {
          "$comment": "Attributes `src` and `srcdoc` are overridden by the `iframe` integrationMode properties",
          "description": "Valid attributes of iframe HTML element",
          "type": "object",
          "additionalProperties": { "type": "string" }
        }
      },
      "additionalProperties": false
    },
    "composableApplication": {
      "title": "ComposableApplication",
      "type": "object",
      "examples": [
        {
          "integrationMode": "compose",
          "config": "./page-configuration.json",
          "route": "/composed-page"
        },
        {
          "integrationMode": "compose",
          "config": {
            "content": {
              "tag": "div"
            }
          },
          "route": "/composed-page"
        }
      ],
      "properties": {
        "integrationMode": {
          "description": "Type of the application: composition of HTML tags",
          "const": "compose"
        },
        "config": {
          "oneOf": [
            {
              "$ref": "https://raw.githubusercontent.com/micro-lc/micro-lc/main/packages/interfaces/schemas/v2/plugin.schema.json#",
              "description": "Composer configuration. It can be an url or an in-line configuration"
            },
            {
              "type": "string",
              "format": "uri-reference"
            }
          ]
        },
        "route": {
          "description": "Path on which the plugin will be rendered",
          "type": "string"
        },
        "options": {
          "title": "ComposableApplicationOptions",
          "type": "object",
          "properties": {
            "fetchConfigOnMount": {
              "description": "Whether of not application config should be fetch on each mount",
              "type": "boolean"
            }
          }
        }
      },
      "additionalProperties": false
    },

    "parcelApplicationEntry": {
      "title": "ParcelApplicationEntry",
      "description": "Entry of the plugin",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "scripts": {
                  "oneOf": [
                    {
                      "type": "string",
                      "format": "uri-reference"
                    },
                    {
                      "type": "array",
                      "items": {
                        "type": "string",
                        "format": "uri-reference"
                      },
                      "minItems": 1
                    }
                  ]
                },
                "styles": {
                  "oneOf": [
                    {
                      "type": "string",
                      "format": "uri-reference"
                    },
                    {
                      "type": "array",
                      "items": {
                        "type": "string",
                        "format": "uri-reference"
                      }
                    }
                  ]
                },
                "html": {
                  "type": "string",
                  "format": "uri-reference"
                }
              },
              "additionalProperties": false,
              "required": ["scripts"]
            },
            {
              "type": "object",
              "properties": {
                "scripts": {
                  "oneOf": [
                    {
                      "type": "string",
                      "format": "uri-reference"
                    },
                    {
                      "type": "array",
                      "items": {
                        "type": "string",
                        "format": "uri-reference"
                      }
                    }
                  ]
                },
                "styles": {
                  "oneOf": [
                    {
                      "type": "string",
                      "format": "uri-reference"
                    },
                    {
                      "type": "array",
                      "items": {
                        "type": "string",
                        "format": "uri-reference"
                      }
                    }
                  ]
                },
                "html": {
                  "type": "string",
                  "format": "uri-reference"
                }
              },
              "additionalProperties": false,
              "required": ["html"]
            }
          ]
        }
      ]
    },

    "parcelApplication": {
      "title": "ParcelApplication",
      "type": "object",
      "examples": [
        {
          "integrationMode": "parcel",
          "route": "/parcel-plugin",
          "entry": "https://my-micro-frontend.com",
          "properties": {
            "foo": "bar"
          }
        }
      ],
      "properties": {
        "integrationMode": {
          "description": "Type of the application: micro front-end loaded using parcels",
          "const": "parcel"
        },
        "entry": {
          "$ref": "#/definitions/parcelApplicationEntry"
        },
        "route": {
          "description": "parcel activeRule",
          "type": "string"
        },
        "properties": {
          "description": "Data passed to the plugin",
          "type": "object"
        },
        "injectBase": {
          "description": "Whether to inject a base tag according to the application given route. Can be used when an hash router is not available",
          "default": false,
          "oneOf": [
            {
              "description": "When true it will attempt to inject a base tag if not already present",
              "type": "boolean",
              "default": false
            },
            {
              "description": "Injects a base tag removing other base tags",
              "const": "override"
            }
          ]
        }
      },
      "additionalProperties": false
    },

    "application": {
      "title": "Application",
      "oneOf": [
        {
          "$ref": "#/definitions/iframeApplication",
          "type": "object",
          "required": ["integrationMode", "route"]
        },
        {
          "$ref": "#/definitions/composableApplication",
          "type": "object",
          "required": ["integrationMode", "config", "route"]
        },
        {
          "$ref": "#/definitions/parcelApplication",
          "type": "object",
          "required": ["integrationMode", "entry", "route"]
        }
      ]
    }
  },
  "type": "object",
  "properties": {
    "version": {
      "const": 2
    },

    "settings": {
      "$ref": "#/definitions/settings",
      "description": "Global micro-lc settings"
    },

    "shared": {
      "type": "object",
      "properties": {
        "properties": {
          "type": "object"
        }
      }
    },

    "importmap": {
      "$ref": "https://raw.githubusercontent.com/micro-lc/micro-lc/main/packages/interfaces/schemas/v2/plugin.schema.json#/definitions/importmap",
      "title": "GlobalImportMap",
      "description": "Global import map"
    },

    "applications": {
      "description": "List of mounted applications",
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/application"
      }
    },

    "layout": {
      "$ref": "https://raw.githubusercontent.com/micro-lc/micro-lc/main/packages/interfaces/schemas/v2/plugin.schema.json#",
      "description": "Orchestrator main page layout DOM configuration",
      "default": {
        "content": {
          "tag": "div",
          "attributes": {
            "id": "__MICRO_LC_MOUNT_POINT"
          }
        }
      },
      "examples": [
        {
          "content": {
            "tag": "div",
            "attributes": {
              "id": "my-plugin-container"
            }
          }
        },
        {
          "sources": "./my-static.js",
          "content": [
            {
              "tag": "my-custom-menu"
            },
            {
              "tag": "div",
              "attributes": {
                "id": "__MICRO_LC_MOUNT_POINT"
              }
            },
            {
              "tag": "my-custom-footer"
            }
          ]
        }
      ]
    }
  },
  "required": ["version"]
}

=== mia-platform/micro-lc/playground/backoffice/config.json
{
  "$schema": "../../packages/interfaces/schemas/v2/config.schema.json",
  "version": 2,
  "shared": {
    "properties": {
      "headers": {
        "key": "value"
      }
    }
  },
  "settings": {
    "defaultUrl": "./home",
    "mountPointSelector": "#__custom_micro_lc",
    "mountPoint": {
      "tag": "mlc-loading-animation",
      "attributes": {
        "id": "__custom_micro_lc",
        "primary-color": "#cd1c8c"
      }
    }
  },
  "importmap": {
    "imports": {
      "rxjs": "https://cdn.jsdelivr.net/npm/@esm-bundle/rxjs@7.5.6/esm/es2015/rxjs.min.js"
    }
  },
  "layout": {
    "sources": {
      "importmap": {
        "imports": {
          "react": "https://esm.sh/react@18.2.0",
          "react-dom": "https://esm.sh/react-dom@18.2.0"
        },
        "scopes": {
          "https://esm.sh/react-dom@next": {
            "/client": "https://esm.sh/react-dom@18.2.0/client"
          }
        }
      },
      "uris": [
        "/packages/layout/dist/mlc-layout.min.js",
        "/packages/layout/dist/mlc-antd-theme-manager.min.js"
      ]
    },
    "content": [
      {
        "tag": "mlc-antd-theme-manager",
        "attributes": {
          "primary-color": "#cd1c8c"
        },
        "properties": {
          "varsPrefix": ["micro-lc", "back-kit", "microlc"]
        }
      },
      {
        "tag": "mlc-layout",
        "content": {
          "tag": "div",
          "content": "PE$",
          "attributes": { "slot": "top-bar" }
        },
        "properties": {
          "userMenu": {
            "userInfoUrl": "./userinfo.json"
          },
          "logo": {
            "url": "/packages/orchestrator/public/favicon.png",
            "onClickHref": "/playground/backoffice/home"
          },
          "mode": "fixedSideBar",
          "menuItems": [
            {
              "icon": {
                "library": "@ant-design/icons-svg",
                "selector": "BugOutlined"
              },
              "id": "main",
              "label": { "en": "Application 1", "it": "Applicazione 1" },
              "type": "application"
            },
            {
              "href": "https://docs.mia-platform.eu",
              "id": "href_1",
              "label": "Link 1",
              "target": "_blank",
              "type": "href"
            },
            {
              "id": "srcdoc",
              "label": "SRCDOC",
              "type": "application"
            },
            {
              "children": [
                {
                  "id": "plain",
                  "selectedAlsoOn": ["plain_details", "plain_about"],
                  "label": "Inline",
                  "type": "application"
                },
                {
                  "id": "composer_new",
                  "label": "Composer V2",
                  "type": "application"
                },
                {
                  "id": "composer_old",
                  "label": "Composer V1",
                  "type": "application"
                },
                {
                  "children": [
                    {
                      "id": "react",
                      "label": "React",
                      "type": "application"
                    },
                    {
                      "href": "./www.google.com",
                      "id": "href_2",
                      "label": "Link 2",
                      "target": "_blank",
                      "type": "href"
                    }
                  ],
                  "id": "group_1",
                  "label": { "en": "Group 1", "it": "Gruppo 1" },
                  "type": "group"
                }
              ],
              "id": "category_1",
              "label": { "en": "Category 1", "it": "Categoria 1" },
              "type": "category"
            }
          ]
        }
      }
    ]
  },
  "applications": {
    "home": {
      "integrationMode": "iframe",
      "route": "./home",
      "src": "https://docs.mia-platform.eu"
    },
    "main": {
      "integrationMode": "iframe",
      "route": "./main",
      "src": "https://wikipedia.org"
    },
    "srcdoc": {
      "integrationMode": "iframe",
      "route": "./srcdoc",
      "srcdoc": "<!DOCTYPE><html><head></head><body>IFrame Content</body></html>"
    },
    "emptyFrame": {
      "integrationMode": "iframe",
      "route": "./empty-frame"
    },
    "react": {
      "integrationMode": "parcel",
      "injectBase": true,
      "route": "./:app/react/",
      "entry": "http://localhost:8003/"
    },
    "main2": {
      "integrationMode": "compose",
      "route": "./main2",
      "config": {
        "sources": {
          "uris": "data:text/javascript;base64,CmltcG9ydCB7UmVwbGF5U3ViamVjdH0gZnJvbSAncnhqcycKCmNvbnNvbGUubG9nKFJlcGxheVN1YmplY3QpCg=="
        },
        "content": {
          "tag": "div",
          "properties": { "textContent": "Ciao Main" }
        }
      }
    },
    "plain": {
      "integrationMode": "compose",
      "route": "./ingredients/",
      "config": {"content": {"tag": "strong", "content": "Home üè†"}}
    },
    "plain_details": {
      "integrationMode": "compose",
      "route": "./ingredients/details/",
      "config": {"content": {"tag": "div", "content": "Hello üëã"}}
    },
    "plain_about": {
      "integrationMode": "compose",
      "route": "./ingredients/about/",
      "config": {"content": {"tag": "div", "content": "About üìì"}}
    },
    "composer_new": {
      "integrationMode": "compose",
      "route": "./:app/ingredients/",
      "config": "./ingredients_v2.json"
    },
    "composer_old": {
      "integrationMode": "parcel",
      "entry": "/element-composer/",
      "route": "./ingredients_old",
      "properties": {
        "configurationName": "../../../../ingredients_v1"
      }
    }
  }
}

=== mia-platform/micro-lc/packages/interfaces/schemas/v2/__tests__/test.json
{
  "$schema": "../config.schema.json",
  "version": 2,
  "applications": {
    "parcel": {
      "integrationMode": "parcel",
      "route": "/route",
      "entry": {
        "html": "index.html",
        "scripts": ["asd"]
      }
    }
  },
  "importmap": {
    "imports": {
      "a": "/a-1.mjs",
      "b": "/b-1.mjs",
      "c": "/c-1.mjs"
    },
    "scopes": {
      "/scope2/": {
        "a": "/a-2.mjs"
      },
      "/scope2/scope3/": {
        "b": "/b-3.mjs"
      }
    }
  },
  "layout": {
    "sources": "banana",
    "content": [
      {
        "tag": "div",
        "attributes": {
          "style": "padding: 0;"
        },
        "content": "Hello!"
      },
      {
        "tag": "slot"
      }
    ]
  }
}
